[package]
name = "inverse-kinematics"
authors = ["Maxwase <max.vvase@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.33" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
